### ISSUE TITLE
Szép napot Tanár úr! készen van a python beadandó

### ISSUE THREAD

**Issue by nagyzsombor05** [Teaching-projects/januari-beadando-nagyzsombor05#1]
a program egy:
szorzás osztás összeadás kivonás gyakorló ami kezeli ha nem kap inputot és a végén elmenti hogy hányszor lett eltalálva vagy elhibázva(ha az osztás nem jön ki egészre pl.: 29/3 akkor 10 re azaz egészre kell  kerekíteni)

**Comment by hegyhati** [comment]
Rendben van, otos.
